create basic cypress workflow
freeCodeCamp/coderadio-client pull request #138
Opened 2021-03-26 18:35 UTC by ahmadabdolsaheb

Checklist:

- [ ] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

2021-03-28 18:40 UTC, huyenltnguyen commented on .github/workflows/cypress
> +name: Cypress Tests
According to [the doc](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows), I think we need to make the file a .yaml one.

2021-03-29 11:24 UTC, raisedadead reviewed
If we are adding a template let's put in some more efforts and model something on the main repo's template instead with at least one meanigful test.

2021-04-08 08:15 UTC, ojeytonwilliams requested changes

2021-04-08 08:15 UTC, ojeytonwilliams commented on .github/workflows/cypress.yml
> +    runs-on: ubuntu-18.04
```suggestion
    # matching current Netlify build environment
    runs-on: ubuntu-16.04
```
Netlify builds in 16.04, so I think it makes sense to match that.

2021-04-08 08:15 UTC, ojeytonwilliams commented on .github/workflows/cypress.yml
> +        node-version: [14.x]
Can we pin this in the package.json via the `engines` property?

```
  "engines": {
    "node": "^14.0.0",
    "npm": "^6.14.12"
  }
```
for example.

I went ahead and set  `NODE_VERSION=14` in Netlify, so the next build should use it.

2021-04-08 08:58 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2021-04-08 09:03 UTC, merged